---
- name: Essential packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    # CLI programs
    - git
    - vim
    - tmux
    - neofetch
    - curl
    - htop
    - ranger
    - build-essential
    - openjdk-8-jdk

    # GUI programs
    - chromium-browser
    - vlc
    - virtualbox
    - baobab
    - transmission

    # other
    - tlp
    - ubuntu-restricted-extras
    

    # codium or code (codium is preferred)
    # terraform
    # vagrant
    # skype
    # libreoffice
    # telegram
    # spotify
    # powershell
    # rtm
    # gitkraken 
  when: ansible_distribution == "Ubuntu"
...
