---
# defaults file for essential-packages-role
essential_packages:
  # CLI programs
  - git
  - vim
  - tmux
  - zsh
  - neofetch
  - curl
  - htop
  - ranger
  - build-essential
  - openjdk-8-jdk

  # GUI programs
  - vlc
  - virtualbox
  - baobab
  - transmission
  - libreoffice

  # other
  - tlp
    
essential_packages_debian:
  - chromium

essential_packages_ubuntu:
  - chromium-browser
  - ubuntu-restricted-extras

# TODO here are more packages that i'd like to install
  # codium or code (codium is preferred)
  # insync
  # spotify
  # skype
  # telegram
  # terraform
  # vagrant
  # powershell
  # rtm

